version: "3.9"

services:
  kds-backend:
    build: .             # use current directory
    container_name: kds-backend
    ports:
      - "3001:3001"      # Updated port
    env_file:
      - ./.env           # use current directory
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: kds-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
